apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fcdj6rh0f-java-quarkus
  janus-idp.io/tekton: fcdj6rh0f-java-quarkus
  backstage.io/kubernetes-id: fcdj6rh0f-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fcdj6rh0f-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
